### ISSUE TITLE
Mismatch between event limit elif cases and the displayed limit types.

### ISSUE THREAD

**Issue by shedfly** [trombastic/PyScada#13]
https://github.com/trombastic/PyScada/blob/c6d7f333f056998f3ab02bf06f692059af1856cd/pyscada/models.py#L1221

displayed order in the web selection drop down.
    limit_type_choices = (
        (0, 'value is less than limit',),
        (1, 'value is less than or equal to the limit',),
        (2, 'value is greater than the limit'),
        (3, 'value is greater than or equal to the limit'),
        (4, 'value equals the limit'),
)

The implemented cases seem to be:
0 = less than
1 = less than or equals to 
2 = equals to
3 = greater than or equals to
4 = greater than

**Comment by trombastic** [comment]
Dear shedfly,

thank you very much for the hint, you are right, 2 and 4 are interchanged, i will fix it in the next version (0.7.0rc12).

king regards,
Martin
