### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cwraig** [trombastic/PyScada#16]
Based on: 
https://pyscada.readthedocs.io/en/dev-0.7.x/django_settings.html
When running command:
sudo -u pyscada python manage.py pyscada_daemon init

Gives the following:
Warning: please change 'pyscada' to 'pyscada.core' in the INSTALLED_APPS section of the settings.py!

Please update the documentation to reflect the change.
I have tested this on a new installation on rasbian.

**Comment by trombastic** [comment]
Dear cwraig,
i'm sorry for the late replay, i updated the Documentation according to your suggestion, it will be included in version 0.7.0rc13
