### ISSUE TITLE
Unable to re login from login screen

### ISSUE THREAD

**Issue by paulalting** [trombastic/PyScada#22]
I am able to log out from PyScada successfully, and am presented with the login screen, where I would expect to be able to re-login after entering username and password.
This is not the case. It simply presents the same login screen again.

I have tried this in Opera ver 57.x as well as Firefox 60.6.1esr, with both doing the same thing, and I am fairly sure this is not a browser related issue.

The only way to re-login is to click on the PyScada menu item at the top left corner.
But this opens another tab.

**Comment by trombastic** [comment]
Dear Paul,

thank you very much for submitting this issue, this will be fixed in the next release.

regards,
Martin
