### ISSUE TITLE
Command-line ERRORs

### ISSUE THREAD

**Issue by SHIVAPRASAD96** [trombastic/PyScada#3]
After installing all dependencies , When head towards Command-line and then ,

ISSUE 1 :
When i run the Command : service gunicorn_pyscada start
I am getting the following Error:
gunicorn_pyscada: unrecognized service

ISSUE 2:
when i run : ** systemctl start "pyscada_* **
i get **Failed to get D-Bus connection: Failed to connect to socket /run/systemd/private: No such file or directory
**
Kindly Respond for the above Queries , Eagerly waiting for the answers because company project has been halted for the same

**Comment by trombastic** [comment]
can you please specify the
 - operating system used
 - installed PyScada version
 - used init system (SysV-init, systemd or upstart)

in the second command a " is missing at the end
