### ISSUE TITLE
Can pyscada act as modbus tcp server

### ISSUE THREAD

**Issue by fengdexunmi** [trombastic/PyScada#32]
@trombastic  Hi, PyScada is of great use for us. But can I use pyscada to setup a **modbus tcp server** ( the modbus device act as **modbus client**, while pyscada act as **server**) ? 
Look forward to receiving your reply.

**Comment by trombastic** [comment]
no at the moment only the **modbus client** mode is implemented, but you can use the **scripting plugin** or write a new dedicated plugin to implement it your own.
regards
martin
