### ISSUE TITLE
Modbus write into a Force Single Coil (FC5)

### ISSUE THREAD

**Issue by jcivitel** [trombastic/PyScada#37]
Hello everybody,
hello @trombastic,

is there a possibility to write into a Single Coil?
I want to use Pyscada to turn on a digitaloutput of a Wago module.

If this isnt currently implemented, could you tell me where I can create my own Modbus Functions?

regards
Jan

**Comment by clavay** [comment]
Hello,
Sorry for the delay.
I think it should work if you select the FC1 in modus variable/function code read
Set the variable as writeable and try to write.

cheers
cla
