### ISSUE TITLE
Could not receive modbus data.

### ISSUE THREAD

**Issue by durvesh09** [trombastic/PyScada#4]
i have setup the PyScada on Raspberry pi. and  i want  to communicate it with modbus over tcp. I can loginmto PyScada admin page, but dont know how to send and receive data over modbus

**Comment by bluesunshinesunny** [comment]
hello @durvesh09 ,do you have any idea to solve the problem？i met the same question yet

**Comment by apanasara** [comment]
Working on PySCADA for plant/process simulation on HMI, where status can be displayed & actuation can be sent ....

For this, I am opting Custom HTML Panel, but I am not able to get data into panel
