### ISSUE TITLE
Support for i2c device such as ADS1115

### ISSUE THREAD

**Issue by shmrymbd** [trombastic/PyScada#8]
Hi,
could you share how to read analog value using ADS1115. thanks

**Comment by trombastic** [comment]
Dear @shmrymbd, unfortunitly i didn't have the time nor i have this device to implement it, but maybe you could add it by your self, at PyScada/pyscada/smbus/device_templates/ups_pico.py is a example for a i2c device that you can use as a template for the ADS1115.
regards,
Martin
